name: github Action CI
on:
  push:
    branches: [ develop, ch-setup-gh-ci ]
      
  pull_request:
    branches: [ develop, ch-setup-gh-ci ]
     
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

